package kansallispuistot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kansallispuistot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.07 18:35:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KommenttiTest {


  // Generated by ComTest BEGIN
  /** testToString52 */
  @Test
  public void testToString52() {    // Kommentti: 52
    Kommentti kommentti = new Kommentti(); 
    kommentti.parse("   2   |  10  |   Kalastus"); 
    //assertEquals("From: Kommentti line: 55", true, kommentti.toString().startsWith("2|10|Kalastus|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi123 */
  @Test
  public void testRekisteroi123() {    // Kommentti: 123
    Kommentti pitsi1 = new Kommentti(); 
    assertEquals("From: Kommentti line: 125", 0, pitsi1.getTunnusNro()); 
    pitsi1.rekisteroi(); 
    Kommentti pitsi2 = new Kommentti(); 
    pitsi2.rekisteroi(); 
    int n1 = pitsi1.getTunnusNro(); 
    int n2 = pitsi2.getTunnusNro(); 
    assertEquals("From: Kommentti line: 131", n2-1, n1); 
  } // Generated by ComTest END
}