package kansallispuistot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kansallispuistot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.10.25 16:28:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReittiTest {
    /*public void testRekisteroi66() {
        Reitti reitti1 = new Reitti();
        assertEquals("From: Reitti line: 68 ", 0, reitti1.getId());
        reitti1.rekisteroi();
        Reitti reitti2 = new Reitti();
        reitti2.rekisteroi();
        int n1 = reitti1.getId();
        int n2 = reitti2.getId();
        n2 === n1+1;
    }*/

}