package kansallispuistot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kansallispuistot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.05 10:56:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReittiTest {



  // Generated by ComTest BEGIN
  /** testToString64 */
  @Test
  public void testToString64() {    // Reitti: 64
    Reitti reitti = new Reitti(); 
    reitti.parse("   1  |  Karhunkierros   | Tuomiojärvi"); 
    assertEquals("From: Reitti line: 67", true, reitti.toString().startsWith("1|Karhunkierros|Tuomiojärvi|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi130 */
  @Test
  public void testRekisteroi130() {    // Reitti: 130
    Reitti reitti1 = new Reitti(); 
    assertEquals("From: Reitti line: 132", 0, reitti1.getId()); 
    reitti1.rekisteroi(); 
    Reitti reitti2 = new Reitti(); 
    reitti2.rekisteroi(); 
    int n1 = reitti1.getId(); 
    int n2 = reitti2.getId(); 
    assertEquals("From: Reitti line: 138", n1+1, n2); 
  } // Generated by ComTest END
}