package kansallispuistot.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kansallispuistot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.08 13:30:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReititTest {



  // Generated by ComTest BEGIN
  /** 
   * testEtsi211 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi211() throws SailoException {    // Reitit: 211
    Reitit jasenet = new Reitit(); 
    Reitti jasen1 = new Reitti(); jasen1.parse("1|Ankka Aku|030201-115H|Paratiisitie 13|"); 
    Reitti jasen2 = new Reitti(); jasen2.parse("2|Ankka Tupu||030552-123B|"); 
    Reitti jasen3 = new Reitti(); jasen3.parse("3|Susi Sepe|121237-121V||131313|Perämetsä"); 
    Reitti jasen4 = new Reitti(); jasen4.parse("4|Ankka Iines|030245-115V|Ankkakuja 9"); 
    Reitti jasen5 = new Reitti(); jasen5.parse("5|Ankka Roope|091007-408U|Ankkakuja 12"); 
    jasenet.lisaa(jasen1); jasenet.lisaa(jasen2); jasenet.lisaa(jasen3); jasenet.lisaa(jasen4); jasenet.lisaa(jasen5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa236 */
  @Test
  public void testLisaa236() {    // Reitit: 236
    Reitit reitit = new Reitit(); 
    //Reitti karhunkierros1 = new Reitti(), karhunkierros2 = new Reitti(); 
    assertEquals("From: Reitit line: 239", 0, reitit.getLkm()); 
  } // Generated by ComTest END
}